version: '3.3'
services:
  db:
    platform: linux/x86_64 # This is for Apple silicon plantform(arm64) as mysql5.7 image platform is amd64
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    # Where our data will be persisted
    volumes:
      - mysql:/var/lib/mysql
# Names volume
volumes:
  mysql:
    driver: local
